import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildAllBundledCoursesFromDocs,
  type BundledCourseEntry,
} from '../src/app/courses/bundled/build-bundled-courses.spec-helper.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = join(__dirname, '..');
const repoRoot = join(appRoot, '..');
const coursesRoot = join(repoRoot, 'docs', 'courses');
const publicOutDir = join(appRoot, 'public', 'bundled-courses');
const manifestPath = join(appRoot, 'src', 'app', 'courses', 'bundled', 'generated-bundled-courses.ts');

const HEADER = `/* eslint-disable */
// DO NOT EDIT — generated by \`npm run generate:bundled-courses\`
`;

function writeManifest(entries: readonly BundledCourseEntry[]): void {
  const body = `${HEADER}
export type BundledCourseEntry = {
  readonly courseId: string;
  readonly file: string;
  readonly title: string;
};

export const BUNDLED_COURSES: readonly BundledCourseEntry[] = ${JSON.stringify(entries, null, 2)};
`;
  writeFileSync(manifestPath, body, 'utf8');
}

rmSync(publicOutDir, { recursive: true, force: true });
mkdirSync(publicOutDir, { recursive: true });

const built = buildAllBundledCoursesFromDocs(coursesRoot);
const entries: BundledCourseEntry[] = [];

for (const item of built) {
  writeFileSync(
    join(publicOutDir, item.entry.file),
    `${JSON.stringify(item.course, null, 2)}\n`,
    'utf8',
  );
  entries.push(item.entry);
  console.log(`Wrote bundled ${item.entry.file} (${item.entry.courseId})`);
}

writeManifest(entries);
console.log(`Wrote manifest (${entries.length} courses)`);
