import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = join(__dirname, '..');
const repoSchemaPath = join(appRoot, '..', 'docs', 'schemas', 'course.schema.json');
const publicSchemaPath = join(appRoot, 'public', 'schemas', 'course.schema.json');
const generatedDir = join(appRoot, 'src', 'app', 'courses', 'generated');

const GENERATED_HEADER = `/* eslint-disable */
// DO NOT EDIT — generated by \`npm run generate:zod\`
`;

type JsonSchema = Record<string, unknown>;

function loadSchema(): JsonSchema {
  return JSON.parse(readFileSync(repoSchemaPath, 'utf8')) as JsonSchema;
}

function bundleSchema(raw: string): void {
  mkdirSync(dirname(publicSchemaPath), { recursive: true });
  writeFileSync(publicSchemaPath, raw, 'utf8');
}

async function generateTypes(schema: JsonSchema): Promise<void> {
  const ts = await compile(schema, 'CourseDocument', {
    bannerComment: GENERATED_HEADER.trim(),
    additionalProperties: false,
    cwd: dirname(repoSchemaPath),
  });
  writeFileSync(join(generatedDir, 'course.types.ts'), ts, 'utf8');
}

function schemaForDef(root: JsonSchema, defName: string): JsonSchema {
  const defs = root['$defs'] as Record<string, JsonSchema>;
  const def = defs[defName];
  if (!def) {
    throw new Error(`Missing $defs/${defName}`);
  }
  return {
    $schema: root['$schema'],
    ...def,
    $defs: { uuid: defs['uuid'] },
  };
}

const CONTENT_DEF_EXPORT_NAMES: Record<string, string> = {
  theoryContent: 'TheoryContentSchema',
  svgContent: 'SvgContentSchema',
  quizContent: 'QuizContentSchema',
  javascriptContent: 'JavascriptContentSchema',
  sqliteContent: 'SqliteContentSchema',
  regexContent: 'RegexContentSchema',
};

function normalizeZodChunk(code: string): string {
  return code
    .replace(/^import \{ z \} from ["']zod["'];?\s*\n/gm, '')
    .replace(/\bz\.any\(\)/g, 'z.unknown()')
    .trim();
}

function generateContentZod(root: JsonSchema): string {
  const contentDefs = Object.keys(CONTENT_DEF_EXPORT_NAMES);

  const uuidSchema = schemaForDef(root, 'uuid');
  const uuidZod = normalizeZodChunk(
    jsonSchemaToZod(uuidSchema, { name: 'UuidSchema', module: 'esm' }),
  );

  const parts: string[] = [GENERATED_HEADER, `import { z } from 'zod';`, '', uuidZod, ''];

  for (const defName of contentDefs) {
    const mini = schemaForDef(root, defName);
    const zodName = CONTENT_DEF_EXPORT_NAMES[defName];
    const zod = normalizeZodChunk(jsonSchemaToZod(mini, { name: zodName, module: 'esm' }));
    parts.push(zod, '');
  }

  return `${parts.join('\n')}\n`;
}

function writeManualGlueNote(): void {
  const notePath = join(generatedDir, 'README.md');
  writeFileSync(
    notePath,
    `# Generated output

Run \`npm run generate:zod\` from \`vibetest-app/\`.

\`content-schemas.zod.ts\` and \`course.types.ts\` are overwritten.
Step/Course Zod composition lives in \`../course-zod-schema.ts\` (manual discriminated union fallback for \`if/then\`).
`,
    'utf8',
  );
}

async function main(): Promise<void> {
  const raw = readFileSync(repoSchemaPath, 'utf8');
  const schema = loadSchema();

  bundleSchema(raw);
  mkdirSync(generatedDir, { recursive: true });

  writeFileSync(
    join(generatedDir, 'content-schemas.zod.ts'),
    generateContentZod(schema),
    'utf8',
  );
  await generateTypes(schema);
  writeManualGlueNote();

  console.log('Generated course schema bundle, Zod content defs, and TypeScript types.');
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
