import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'src', 'app', 'shared', 'build-info', 'generated-build-info.ts');

const HEADER = `/* eslint-disable */
// DO NOT EDIT — generated by \`npm run generate:build-info\`
`;

function gitOutput(args: string): string | null {
  try {
    return execSync(`git ${args}`, {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return null;
  }
}

const commitShort = gitOutput('rev-parse --short HEAD') ?? 'unknown';
const commitSubject = gitOutput('log -1 --format=%s') ?? 'dev';

const body = `${HEADER}
export interface BuildInfo {
  readonly commitShort: string;
  readonly commitSubject: string;
}

export const BUILD_INFO: BuildInfo = {
  commitShort: ${JSON.stringify(commitShort)},
  commitSubject: ${JSON.stringify(commitSubject)},
};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body, 'utf8');
console.log(`Wrote build info: ${commitShort} · ${commitSubject}`);
