import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { buildModuleImportSchemaFromCourseImport } from './build-module-import-schema.mts';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = join(__dirname, '..');
const repoSchemaPath = join(appRoot, '..', 'docs', 'schemas', 'course.schema.json');
const repoImportSchemaPath = join(appRoot, '..', 'docs', 'schemas', 'course-import.schema.json');
const repoModuleImportSchemaPath = join(
  appRoot,
  '..',
  'docs',
  'schemas',
  'module-import.schema.json',
);
const publicSchemaPath = join(appRoot, 'public', 'schemas', 'course.schema.json');
const publicImportSchemaPath = join(appRoot, 'public', 'schemas', 'course-import.schema.json');
const publicModuleImportSchemaPath = join(
  appRoot,
  'public',
  'schemas',
  'module-import.schema.json',
);
const repoOutlineSchemaPath = join(
  appRoot,
  '..',
  'docs',
  'schemas',
  'course-outline.schema.json',
);
const publicOutlineSchemaPath = join(appRoot, 'public', 'schemas', 'course-outline.schema.json');
const generatedDir = join(appRoot, 'src', 'app', 'courses', 'generated');
const outlineGeneratedDir = join(appRoot, 'src', 'app', 'course-generation', 'generated');

const GENERATED_HEADER = `/* eslint-disable */
// DO NOT EDIT — generated by \`npm run generate:zod\`
`;

type JsonSchema = Record<string, unknown>;

function loadSchema(): JsonSchema {
  return JSON.parse(readFileSync(repoSchemaPath, 'utf8')) as JsonSchema;
}

function bundleSchema(raw: string): void {
  mkdirSync(dirname(publicSchemaPath), { recursive: true });
  writeFileSync(publicSchemaPath, raw, 'utf8');
}

async function generateTypes(schema: JsonSchema): Promise<void> {
  const ts = await compile(schema, 'CourseDocument', {
    bannerComment: GENERATED_HEADER.trim(),
    additionalProperties: false,
    cwd: dirname(repoSchemaPath),
  });
  writeFileSync(join(generatedDir, 'course.types.ts'), ts, 'utf8');
}

function schemaForDef(root: JsonSchema, defName: string): JsonSchema {
  const defs = root['$defs'] as Record<string, JsonSchema>;
  const def = defs[defName];
  if (!def) {
    throw new Error(`Missing $defs/${defName}`);
  }
  return {
    $schema: root['$schema'],
    ...def,
    $defs: { uuid: defs['uuid'] },
  };
}

const CONTENT_DEF_EXPORT_NAMES: Record<string, string> = {
  theoryContent: 'TheoryContentSchema',
  svgContent: 'SvgContentSchema',
  quizContent: 'QuizContentSchema',
  javascriptContent: 'JavascriptContentSchema',
  sqliteContent: 'SqliteContentSchema',
  regexContent: 'RegexContentSchema',
};

function normalizeZodChunk(code: string): string {
  return code
    .replace(/^import \{ z \} from ["']zod["'];?\s*\n/gm, '')
    .replace(/\bz\.any\(\)/g, 'z.unknown()')
    .trim();
}

function generateContentZod(root: JsonSchema): string {
  const contentDefs = Object.keys(CONTENT_DEF_EXPORT_NAMES);

  const uuidSchema = schemaForDef(root, 'uuid');
  const uuidZod = normalizeZodChunk(
    jsonSchemaToZod(uuidSchema, { name: 'UuidSchema', module: 'esm' }),
  );

  const parts: string[] = [GENERATED_HEADER, `import { z } from 'zod';`, '', uuidZod, ''];

  for (const defName of contentDefs) {
    const mini = schemaForDef(root, defName);
    const zodName = CONTENT_DEF_EXPORT_NAMES[defName];
    const zod = normalizeZodChunk(jsonSchemaToZod(mini, { name: zodName, module: 'esm' }));
    parts.push(zod, '');
  }

  return `${parts.join('\n')}\n`;
}

/** json-schema-to-zod leaves `$ref` as unknown; inline local `#/$defs/*` refs (schema must be acyclic). */
function inlineLocalRefs(node: unknown, defs: Record<string, unknown>): unknown {
  if (Array.isArray(node)) {
    return node.map((item) => inlineLocalRefs(item, defs));
  }
  if (node === null || typeof node !== 'object') {
    return node;
  }
  const record = node as Record<string, unknown>;
  const ref = record['$ref'];
  if (typeof ref === 'string' && ref.startsWith('#/$defs/')) {
    const def = defs[ref.slice('#/$defs/'.length)];
    if (def === undefined) {
      throw new Error(`Missing ${ref}`);
    }
    return inlineLocalRefs(def, defs);
  }
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (key !== '$defs') {
      result[key] = inlineLocalRefs(value, defs);
    }
  }
  return result;
}

function generateOutlineZod(outlineSchema: JsonSchema): string {
  const defs = (outlineSchema['$defs'] ?? {}) as Record<string, unknown>;
  const inlined = inlineLocalRefs(outlineSchema, defs) as JsonSchema;
  const zod = normalizeZodChunk(
    jsonSchemaToZod(inlined, { name: 'CourseOutlineSchema', module: 'esm' }),
  );
  return `${[GENERATED_HEADER, `import { z } from 'zod';`, '', zod].join('\n')}\n`;
}

function writeOutlineBundle(): void {
  const outlineRaw = readFileSync(repoOutlineSchemaPath, 'utf8');
  writeFileSync(publicOutlineSchemaPath, outlineRaw, 'utf8');
  mkdirSync(outlineGeneratedDir, { recursive: true });
  writeFileSync(
    join(outlineGeneratedDir, 'course-outline.zod.ts'),
    generateOutlineZod(JSON.parse(outlineRaw) as JsonSchema),
    'utf8',
  );
}

function writeManualGlueNote(): void {
  const notePath = join(generatedDir, 'README.md');
  writeFileSync(
    notePath,
    `# Generated output

Run \`npm run generate:zod\` from \`vibetest-app/\`.

\`content-schemas.zod.ts\` and \`course.types.ts\` are overwritten.
Step/Course Zod composition lives in \`../course-zod-schema.ts\` (manual discriminated union fallback for \`if/then\`).
`,
    'utf8',
  );
}

async function main(): Promise<void> {
  const raw = readFileSync(repoSchemaPath, 'utf8');
  const importRaw = readFileSync(repoImportSchemaPath, 'utf8');
  const importSchema = JSON.parse(importRaw) as JsonSchema;
  const moduleImportRaw = `${JSON.stringify(buildModuleImportSchemaFromCourseImport(importSchema), null, 2)}\n`;
  writeFileSync(repoModuleImportSchemaPath, moduleImportRaw, 'utf8');
  const schema = loadSchema();

  bundleSchema(raw);
  mkdirSync(dirname(publicImportSchemaPath), { recursive: true });
  writeFileSync(publicImportSchemaPath, importRaw, 'utf8');
  writeFileSync(publicModuleImportSchemaPath, moduleImportRaw, 'utf8');
  mkdirSync(generatedDir, { recursive: true });

  writeFileSync(
    join(generatedDir, 'content-schemas.zod.ts'),
    generateContentZod(schema),
    'utf8',
  );
  await generateTypes(schema);
  writeOutlineBundle();
  writeManualGlueNote();

  console.log('Generated course schema bundle, Zod content defs, and TypeScript types.');
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
