/* eslint-disable */
// DO NOT EDIT — generated by `npm run generate:build-info`

export interface BuildInfo {
  readonly commitShort: string;
  readonly commitSubject: string;
}

export const BUILD_INFO: BuildInfo = {
  commitShort: "7e7a1e2",
  commitSubject: "vt-36: prompt rules for Markdown code blocks in theory steps.",
};
