/* eslint-disable */
// DO NOT EDIT — generated by `npm run generate:bundled-courses`

export type BundledCourseEntry = {
  readonly courseId: string;
  readonly file: string;
  readonly title: string;
};

export const BUNDLED_COURSES: readonly BundledCourseEntry[] = [
  {
    "courseId": "5feeec7f-06ab-4f92-a27b-9858cdecf5c9",
    "file": "algorithms-blind-75.json",
    "title": "Алгоритмы на JavaScript: Blind 75"
  },
  {
    "courseId": "6bc56204-d1ae-41ec-bee1-e5bf082486de",
    "file": "javascript-for-csharp.json",
    "title": "JavaScript для C#-разработчика"
  }
];
